import { TetyanaAPI } from './contract';
import { ForgeAPI } from '../forge/contract';
import { VoiceAPI } from '../voice/contract';
import { BrainAPI } from '../brain/contract';

export class TetyanaCapsule implements TetyanaAPI {
    private forge: ForgeAPI;
    private voice: VoiceAPI;
    private brain: BrainAPI;

    constructor(forge: ForgeAPI, voice: VoiceAPI, brain: BrainAPI) {
        this.forge = forge;
        this.voice = voice;
        this.brain = brain;
    }

    async execute(args: { tool: string; args: Record<string, any> }) {
        console.log(`TETYANA: Executing ${args.tool}`);
        await this.voice.speak({ text: `Executing ${args.tool}`, voice: 'tetyana' });

        // Ask Brain if this is a safe/valid execution (simplified)
        // or ask Brain to generate the code if the tool is "generate_code"

        const output = await this.forge.execute({ tool_name: args.tool, args: args.args });
        return { success: true, output };
    }

    async forge_tool(args: { name: string; spec: string }) {
        console.log(`TETYANA: Forging tool ${args.name}...`);

        const response = await this.brain.think({
            system_prompt: `You are TETYANA, the Builder. Generate a TypeScript tool named "${args.name}". Return ONLY the code.`,
            user_prompt: `Spec: ${args.spec}`
        });

        const result = await this.forge.synthesize({
            name: args.name,
            description: "Auto-generated by Tetyana via Brain",
            code: response.text || '// Error generating code'
        });
        return result.path || '';
    }
}
