import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import * as schema from './schema';
import path from 'path';

// Standard KONTUR location for data
const DB_PATH = path.resolve(process.cwd(), 'atlas.db');

export function initDB() {
    const sqlite = new Database(DB_PATH);
    const db = drizzle(sqlite, { schema });

    // Auto-migrate on startup for now (simplification for prototype)
    // In production, we would use strict migrations
    // For now we will rely on drizzle-kit push or manual table creation check
    // Actually, let's just create the table via sql execute if not exists for simplicity in this phase
    // since 'migrate' requires a migrations folder generated by kit.

    sqlite.exec(`
      CREATE TABLE IF NOT EXISTS memories (
        id TEXT PRIMARY KEY,
        type TEXT NOT NULL,
        content TEXT NOT NULL,
        embedding BLOB,
        metadata TEXT,
        created_at INTEGER NOT NULL DEFAULT (unixepoch())
      );
    `);

    return db;
}
